### ISSUE TITLE
 Installing GoFreeTds in Windows 7 Error

### ISSUE THREAD

**Issue by mvbaffa** [minus5/gofreetds#15]
I have Already install MinGW gcc is working ok, when I go get -u github.com/minus5/gofreetds I receive this error:

D:\GoLib\src\github.com\minus5\gofreetds\callbacks.go:8:22: fatal error: sybfront.h: No such file or directory
 #include <sybfront.h>
                      ^
compilation terminated.

Can you help me?

**Comment by mvbaffa** [comment]
I have solved with an Environment variable C_INCLUDE_PATH pointing to freetds/include. 
It seems that the problem is my version of Freetds for windows is 32 bit. 

I am getting this error in conn.go:
warning: cast from pointer to integer of different size

This error occurs in three lines: 30:22, 36:22 and 50:10.

I cannot go get gofreetds because freetds cannot compile.

Can you tell where to find the correct freetds source.

Thanks

**Comment by ianic** [comment]
I don't have experience with using freetds on Windows.
On Mac I use homebrew, and on ubuntu apt packages.

According to the lines problem is cgo related.
Did you check the cgo doc about windows, https://github.com/golang/go/wiki/cgo: 
*In order to use cgo on Windows, you'll also need to first install a gcc compiler (for instance, mingw-w64) and have gcc.exe (etc.) in your PATH environment variable before compiling with cgo will work.*
