### ISSUE TITLE
TestExecuteSqlNullString prints the message "unknown dataType *string"

### ISSUE THREAD

**Issue by edharper01** [minus5/gofreetds#49]
Although the test completes as a PASS, `TestExecuteSqlNullString` in conn_test.go prints the message "unknown dataType *string".

Changing the variable declaration on line 458 of conn_test.go to 
`var str string`
suppresses the message, but it's not clear whether this is the expected behaviour. Should the object under test accept a string pointer, or is the test in error?

**Comment by ianic** [comment]
Running test results in this database call:
```
exec sp_executesql N'update dbo.freetds_types set nvarchar_max=@p1 where int = 3;', N'@p1 nvarchar (5)', @p1='<nil>'
```

Null pointer to string is in [executesql.go:77](https://github.com/minus5/gofreetds/blob/master/executesql.go#L77) is formatted as '\<nil>'.
Executing this test results in inserting '\<nil>' string into nvarchar_max column.
That is clearly wrong. If we have support for nullable data types database column should be null.
Currently we don't support nullable data types, as we can see in  [go2SqlDataType](https://github.com/minus5/gofreetds/blob/master/executesql.go#L69).

This test works only for strings. If we try with some other column type we will get something like this:
```
exec sp_executesql N'update dbo.freetds_types set long=@p1 where int = 3;', N'@p1 nvarchar (5)', @p1='<nil>'
```
which results in mssql error: "Error converting data type nvarchar to bigint."

One solution is to upgrade go2SqlDataType to support pointer types. But there will always be types which are not covered. In that case library should return meaningful error instead of logging. 

We (in minus5) are never using ExecuteSql and I'm not sure that adding support for pointer types is good idea. So I will leave that to someone who finds that useful.
But I'm [changing](https://github.com/minus5/gofreetds/commit/8184548938bd0f7c1ba3cb53253ae84d558a61f1) code to return error instead of logging in  case of unsupported data type.

Thanks edharper01 for pointing to this misleading test.
